---
name: Run tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: .github/workflows/requirements.txt

      - name: Apt update
        run: sudo apt update -y

      - name: Install xmllint
        run: |
          sudo apt install --yes libxml2-utils
          xmllint --version

      - name: Install requirements
        run: pip install -r .github/workflows/requirements.txt

      - name: Run tests
        run: pytest
